---
title: "my ver proj"
author: "MEDHASWETA SEN"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
# We want the results to be hidden by default, though for some chunks we will override this to show the results
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
```
```{r}
library(magrittr)
```

```{r results = "show"}
# This is copied form the Kaggle site
data_definitions <- data.frame(variable = c("credit.policy", "purpose", "int.rate", "installment", "log.annual.inc", "dti", "fico", "days.with.cr.line", "revol.bal", "revol.util", "inq.last.6mths", "delinq.2yrs", "pub.rec", "not.fully.paid"),
                          definition = c("1 if the customer meets the credit underwriting criteria of LendingClub.com, and 0 otherwise.",
                                         "The purpose of the loan (takes values creditcard, debtconsolidation, educational, majorpurchase, smallbusiness, and all_other).",
                                         "The interest rate of the loan, as a proportion (a rate of 11% would be stored as 0.11). Borrowers judged by LendingClub.com to be more risky are assigned higher interest rates.",
                                         "The monthly installments owed by the borrower if the loan is funded.",
                                         "The natural log of the self-reported annual income of the borrower.",
                                         "The debt-to-income ratio of the borrower (amount of debt divided by annual income).",
                                         "The FICO credit score of the borrower.",
                                         "The number of days the borrower has had a credit line.",
                                         "The borrower's revolving balance (amount unpaid at the end of the credit card billing cycle).",
                                         "The borrower's revolving line utilization rate (the amount of the credit line used relative to total credit available).",
                                         "The borrower's number of inquiries by creditors in the last 6 months.",
                                         "The number of times the borrower had been 30+ days past due on a payment in the past 2 years.",
                                         "The borrower's number of derogatory public records (bankruptcy filings, tax liens, or judgments).",
                                         "Whether the borrower will be fully paid or not."))

knitr::kable(data_definitions)
```

```{r}
library(ezids) # We will use functions form this package to get nicer looking results
library(tidyverse) # We need this package for data manipulation, pipnig, and graphing
# read_csv vs read.csv
loans <- read.csv("lending_club_loan_data.csv")
```

```{r results = "show"}
# There is unfortunately no ezids function to see the result in a nice looking table, so we will use the standard function.
str(loans)
```

```{r}
dim(loans)
```

```{r results = "show"}
# We use the xkabledplyhead() function form the ezids package to see the result in a nice looking table.
xkabledplyhead(loans)
```

```{r results = "show"}
# We use the xkabledplytail() function form the ezids package to see the result in a nice looking table.
xkabledplytail(loans)
```

```{r results = "show"}
# We use the xkablesummary() function from the ezids package to see the result in a nice looking table.
xkablesummary(loans)
```

```{r}
# By gathering the variables we want to see into a long format with the gather() function, we can then create a histogram
# for each variable using the facet_wrap() function in ggplot2.
loans %>%
  select(int.rate, installment, log.annual.inc, dti, fico, days.with.cr.line, revol.bal, revol.util,
           inq.last.6mths, delinq.2yrs, pub.rec) %>%
  gather(variable, value) %>%
  ggplot(aes(x = value)) +
  geom_histogram(fill = "steelblue", color = "black") +
  facet_wrap(~ variable, scales = "free") + # Free scales so the graphs are readable
  labs(title = "Histograms of Numeric Variables", x = "Value", y = "Count") +
  theme_minimal()
```

```{r}
# By gathering the variables we want to see into a long format with the gather() function, we can then create a boxplot
# for each variable using the facet_wrap() function in ggplot2.
loans %>%
  select(int.rate, installment, log.annual.inc, dti, fico, days.with.cr.line, revol.bal, revol.util,
           inq.last.6mths, delinq.2yrs, pub.rec) %>%
  gather(variable, value) %>%
  ggplot(aes(x = value)) +
  geom_boxplot(fill = "steelblue", color = "black",
               outlier.size = 2, outlier.alpha = 0.2) + # Translucent and larger outliers to help with overplotting
  facet_wrap(~ variable, scales = "free") + # Free scales so the graphs are readable
  labs(title = "Boxplots of Numeric Variables", x = "Value") +
  theme_minimal() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
```

```{r}
# By gathering the variables we want to see into a long format with the gather() function, we can then create a bar graph
# for each variable using the facet_wrap() function in ggplot2.
loans %>%
  select(credit.policy, purpose, not.fully.paid) %>%
  gather(variable, value) %>%
  ggplot(aes(x = value)) +
  geom_bar(fill = "steelblue", color = "black") +
  facet_wrap(~ variable, scales = "free") + # Free scales so the graphs are readable
  labs(title = "Bar Charts of Non-Numeric Variables", x = "Value", y = "Count") +
  theme_minimal() +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1), axis.ticks.x = element_line())
```

```{r results = "Show"}
# We will convert the average to an easier to read percentage by multiplying by 100, rounding, and adding a "%" at the end.
loans %>%
  group_by(credit.policy) %>%
  summarize(percent_not_fully_paid = paste0(round(100*mean(not.fully.paid), 1), "%"))  %>%
  ungroup() %>%
  knitr::kable(align = "c")
```

```{r}
data_definitions_augmented <- data_definitions %>%
  mutate(type = c("Logical", "Factor", "Numeric", "Numeric", "Numeric", "Numeric", "Integer", "Numeric", "Integer", "Numeric", "Integer", "Integer", "Integer", "Logical")) %>%
  select(variable, type, definition)
```

```{r results = "show"}
knitr::kable(data_definitions_augmented)
```

```{r}
loans$credit.policy <- as.logical(loans$credit.policy)
loans$not.fully.paid <- as.logical(loans$not.fully.paid)

loans$purpose <- as.factor(loans$purpose)
```

```{r}
# By gathering the variables we want to see into a long format with the gather() function, we can then create a boxplot
# for each variable using the facet_wrap() function in ggplot2. We can see this for each credit policy value by excluding
# it in the gather() function.
loans %>%
  select(int.rate, installment, log.annual.inc, dti, fico, days.with.cr.line, revol.bal, revol.util,
           inq.last.6mths, delinq.2yrs, pub.rec, credit.policy) %>%
  gather(variable, value, -credit.policy) %>%
  ggplot(aes(x = value, y = as.logical(credit.policy), fill = as.logical(credit.policy))) +
  geom_boxplot(outlier.size = 2, outlier.alpha = 0.2) +  # Translucent and larger outliers to help with overplotting
  guides(fill = guide_legend(reverse = TRUE)) + # So the legend order matches the order in the graphs
  facet_wrap(~ variable, scales = "free_x") + # Free x scale so the graphs are readable
  labs(title = "Boxplots of Numeric Variables", subtitle = "Comparing `credit.policy` Values",
       x = "Value", y = "Count", fill = "Credit Policy") +
  theme_minimal()
```

```{r}
# By gathering the variables we want to see into a long format with the gather() function, we can then create a boxplot
# for each variable using the facet_wrap() function in ggplot2. We can see this for each not fully paid value by excluding
# it in the gather() function.
loans %>%
  select(int.rate, installment, log.annual.inc, dti, fico, days.with.cr.line, revol.bal, revol.util,
           inq.last.6mths, delinq.2yrs, pub.rec, not.fully.paid) %>%
  gather(variable, value, -not.fully.paid) %>%
  ggplot(aes(x = value, y = as.logical(not.fully.paid), fill = as.logical(not.fully.paid))) +
  geom_boxplot(outlier.size = 2, outlier.alpha = 0.2) +  # Translucent and larger outliers to help with overplotting
  guides(fill = guide_legend(reverse = TRUE)) + # So the legend order matches the order in the graphs
  facet_wrap(~ variable, scales = "free_x") + # Free x scale so the graphs are readable
  labs(title = "Boxplots of Numeric Variables", subtitle = "Comparing `not.fully.paid` Values",
       x = "Value", y = "Count", fill = "Not Fully Paid") +
  theme_minimal()
```

```{r}
# By gathering the variables we want to see into a long format with the gather() function, we can then create a boxplot
# for each variable using the facet_wrap() function in ggplot2. We can see this for each purpose value by excluding
# it in the gather() function.
loans %>%
  select(int.rate, installment, log.annual.inc, dti, fico, days.with.cr.line, revol.bal, revol.util,
           inq.last.6mths, delinq.2yrs, pub.rec, purpose) %>%
  gather(variable, value, -purpose) %>%
  ggplot(aes(x = value, y = purpose, fill = purpose)) +
  geom_boxplot(outlier.size = 2, outlier.alpha = 0.2) +
  guides(fill = guide_legend(reverse = TRUE)) + # So the legend order matches the order in the graphs
  facet_wrap(~ variable, scales = "free_x") + # Free x scale so the graphs are readable
  labs(title = "Boxplots of Numeric Variables", subtitle = "Comparing `purpose` Values",
       x = "Value", y = "Count", fill = "Purpose") +
  theme_minimal()
```

```{r}
loadPkg("BSDA")
ztest95rate = z.test(x=loans$int.rate, sigma.x = 2.31) # default conf.level = 0.95
ztest95rate
ztest99rate = z.test(x=loans$int.rate, sigma.x = 2.31, conf.level=0.99 )
ztest99rate
ztest50rate = z.test(x=loans$int.rate, sigma.x = 2.31, conf.level=0.50 )
ztest50rate
ztest99rate$estimate
ztest99rate$statistic
ztest99rate$method
ztest95rate$estimate
ztest95rate$statistic
ztest95rate$method
ztest50rate$estimate
ztest50rate$statistic
ztest50rate$method
```

```{r}
ztest95installment = z.test(x=loans$installment, sigma.x = 2.31) # default conf.level = 0.95
ztest95installment
ztest99installment = z.test(x=loans$installment, sigma.x = 2.31, conf.level=0.99 )
ztest99installment
ztest50installment = z.test(x=loans$installment, sigma.x = 2.31, conf.level=0.50 )
ztest50installment
ztest99installment$estimate
ztest99installment$statistic
ztest99installment$method
ztest95installment$estimate
ztest95installment$statistic
ztest95installment$method
ztest50installment$estimate
ztest50installment$statistic
ztest50installment$method
```

```{r}
ztest95annual = z.test(x=loans$log.annual.inc, sigma.x = 2.31) # default conf.level = 0.95
ztest95annual
ztest99annual = z.test(x=loans$log.annual.inc, sigma.x = 2.31, conf.level=0.99 )
ztest99annual
ztest50annual = z.test(x=loans$log.annual.inc, sigma.x = 2.31, conf.level=0.50 )
ztest50annual
ztest99annual$estimate
ztest99annual$statistic
ztest99annual$method
ztest95annual$estimate
ztest95annual$statistic
ztest95annual$method
ztest50annual$estimate
ztest50annual$statistic
ztest50annual$method
```

```{r}
ztest95fico = z.test(x=loans$fico, sigma.x = 2.31) # default conf.level = 0.95
ztest95fico
ztest99fico = z.test(x=loans$fico, sigma.x = 2.31, conf.level=0.99 )
ztest99fico
ztest50fico = z.test(x=loans$fico, sigma.x = 2.31, conf.level=0.50 )
ztest50fico
ztest99fico$estimate
ztest99fico$statistic
ztest99fico$method
ztest95fico$estimate
ztest95fico$statistic
ztest95fico$method
ztest50fico$estimate
ztest50fico$statistic
ztest50fico$method
```

```{r}
ztest95dti = z.test(x=loans$dti, sigma.x = 2.31) # default conf.level = 0.95
ztest95dti
ztest99dti = z.test(x=loans$dti, sigma.x = 2.31, conf.level=0.99 )
ztest99dti
ztest50dti = z.test(x=loans$dti, sigma.x = 2.31, conf.level=0.50 )
ztest50dti
ztest99dti$estimate
ztest99dti$statistic
ztest99dti$method
ztest95dti$estimate
ztest95dti$statistic
ztest95dti$method
ztest50dti$estimate
ztest50dti$statistic
ztest50dti$method
```

```{r}
ztest95days.with.cr.line = z.test(x=loans$days.with.cr.line, sigma.x = 2.31) # default conf.level = 0.95
ztest95days.with.cr.line
ztest99days.with.cr.line = z.test(x=loans$days.with.cr.line, sigma.x = 2.31, conf.level=0.99 )
ztest99days.with.cr.line
ztest50days.with.cr.line = z.test(x=loans$days.with.cr.line, sigma.x = 2.31, conf.level=0.50 )
ztest50days.with.cr.line
ztest99days.with.cr.line$estimate
ztest99days.with.cr.line$statistic
ztest99days.with.cr.line$method
ztest95days.with.cr.line$estimate
ztest95days.with.cr.line$statistic
ztest95days.with.cr.line$method
ztest50days.with.cr.line$estimate
ztest50days.with.cr.line$statistic
ztest50days.with.cr.line$method
```

```{r}
ztest95revol.bal = z.test(x=loans$revol.bal, sigma.x = 2.31) # default conf.level = 0.95
ztest95revol.bal
ztest99revol.bal = z.test(x=loans$revol.bal, sigma.x = 2.31, conf.level=0.99 )
ztest99revol.bal
ztest50revol.bal = z.test(x=loans$revol.bal, sigma.x = 2.31, conf.level=0.50 )
ztest50revol.bal
ztest99revol.bal$estimate
ztest99revol.bal$statistic
ztest99revol.bal$method
ztest95revol.bal$estimate
ztest95revol.bal$statistic
ztest95revol.bal$method
ztest50revol.bal$estimate
ztest50revol.bal$statistic
ztest50revol.bal$method
```

```{r}
ztest95revol.util = z.test(x=loans$revol.util, sigma.x = 2.31) # default conf.level = 0.95
ztest95revol.util
ztest99revol.util = z.test(x=loans$revol.util, sigma.x = 2.31, conf.level=0.99 )
ztest99revol.util
ztest50revol.util = z.test(x=loans$revol.util, sigma.x = 2.31, conf.level=0.50 )
ztest50revol.util
ztest99revol.util$estimate
ztest99revol.util$statistic
ztest99revol.util$method
ztest95revol.util$estimate
ztest95revol.util$statistic
ztest95revol.util$method
ztest50revol.util$estimate
ztest50revol.util$statistic
ztest50revol.util$method
```

```{r}
ztest95inq.last.6mths = z.test(x=loans$inq.last.6mths, sigma.x = 2.31) # default conf.level = 0.95
ztest95inq.last.6mths
ztest99inq.last.6mths = z.test(x=loans$inq.last.6mths, sigma.x = 2.31, conf.level=0.99 )
ztest99inq.last.6mths
ztest50inq.last.6mths = z.test(x=loans$inq.last.6mths, sigma.x = 2.31, conf.level=0.50 )
ztest50inq.last.6mths
ztest99inq.last.6mths$estimate
ztest99inq.last.6mths$statistic
ztest99inq.last.6mths$method
ztest95inq.last.6mths$estimate
ztest95inq.last.6mths$statistic
ztest95inq.last.6mths$method
ztest50inq.last.6mths$estimate
ztest50inq.last.6mths$statistic
ztest50inq.last.6mths$method
```

```{r}
ztest95delinq.2yrs = z.test(x=loans$delinq.2yrs, sigma.x = 2.31) # default conf.level = 0.95
ztest95delinq.2yrs
ztest99delinq.2yrs = z.test(x=loans$delinq.2yrs, sigma.x = 2.31, conf.level=0.99 )
ztest99delinq.2yrs
ztest50delinq.2yrs = z.test(x=loans$delinq.2yrs, sigma.x = 2.31, conf.level=0.50 )
ztest50delinq.2yrs
ztest99delinq.2yrs$estimate
ztest99delinq.2yrs$statistic
ztest99delinq.2yrs$method
ztest95delinq.2yrs$estimate
ztest95delinq.2yrs$statistic
ztest95delinq.2yrs$method
ztest50delinq.2yrs$estimate
ztest50delinq.2yrs$statistic
ztest50delinq.2yrs$method
```

```{r}
ztest95pub.rec = z.test(x=loans$pub.rec, sigma.x = 2.31) # default conf.level = 0.95
ztest95pub.rec
ztest99pub.rec = z.test(x=loans$pub.rec, sigma.x = 2.31, conf.level=0.99 )
ztest99pub.rec
ztest50pub.rec = z.test(x=loans$pub.rec, sigma.x = 2.31, conf.level=0.50 )
ztest50pub.rec
ztest99pub.rec$estimate
ztest99pub.rec$statistic
ztest99pub.rec$method
ztest95pub.rec$estimate
ztest95pub.rec$statistic
ztest95pub.rec$method
ztest50pub.rec$estimate
ztest50pub.rec$statistic
ztest50pub.rec$method
```

```{r}
ttest95rate = t.test(x=loans$int.rate) # default conf.level = 0.95
ttest95rate
ttest99rate = t.test(x=loans$int.rate, conf.level=0.99 )
ttest99rate
ttest50rate = t.test(x=loans$int.rate, conf.level=0.50 )
ttest50rate
ttest99rate$estimate
ttest99rate$statistic
ttest99rate$method
ttest95rate$estimate
ttest95rate$statistic
ttest95rate$method
ttest50rate$estimate
ttest50rate$statistic
ttest50rate$method
```

```{r}
ttest95installment = t.test(x=loans$installment) # default conf.level = 0.95
ttest95installment
ttest99installment = t.test(x=loans$installment, conf.level=0.99 )
ttest99installment
ttest50installment = t.test(x=loans$installment, conf.level=0.50 )
ttest50installment
ttest99installment$estimate
ttest99installment$statistic
ttest99installment$method
ttest95installment$estimate
ttest95installment$statistic
ttest95installment$method
ttest50installment$estimate
ttest50installment$statistic
ttest50installment$method
```

```{r}
ttest95annual = t.test(x=loans$log.annual.inc) # default conf.level = 0.95
ttest95annual
ttest99annual = t.test(x=loans$log.annual.inc, conf.level=0.99 )
ttest99annual
ttest50annual = t.test(x=loans$log.annual.inc, conf.level=0.50 )
ttest50annual
ttest99annual$estimate
ttest99annual$statistic
ttest99annual$method
ttest95annual$estimate
ttest95annual$statistic
ttest95annual$method
ttest50annual$estimate
ttest50annual$statistic
ttest50annual$method
```

```{r}
ttest95fico = t.test(x=loans$fico) # default conf.level = 0.95
ttest95fico
ttest99fico = t.test(x=loans$fico, conf.level=0.99 )
ttest99fico
ttest50fico = t.test(x=loans$fico, conf.level=0.50 )
ttest50fico
ttest99fico$estimate
ttest99fico$statistic
ttest99fico$method
ttest95fico$estimate
ttest95fico$statistic
ttest95fico$method
ttest50fico$estimate
ttest50fico$statistic
ttest50fico$method
```

```{r}
ttest95dti = t.test(x=loans$dti) # default conf.level = 0.95
ttest95dti
ttest99dti = t.test(x=loans$dti, conf.level=0.99 )
ttest99dti
ttest50dti = t.test(x=loans$dti, conf.level=0.50 )
ttest50dti
ttest99dti$estimate
ttest99dti$statistic
ttest99dti$method
ttest95dti$estimate
ttest95dti$statistic
ttest95dti$method
ttest50dti$estimate
ttest50dti$statistic
ttest50dti$method
```

```{r}
ttest95days.with.cr.line = t.test(x=loans$days.with.cr.line) # default conf.level = 0.95
ttest95days.with.cr.line
ttest99days.with.cr.line = t.test(x=loans$days.with.cr.line, conf.level=0.99 )
ttest99days.with.cr.line
ttest50days.with.cr.line = t.test(x=loans$days.with.cr.line, conf.level=0.50 )
ttest50days.with.cr.line
ttest99days.with.cr.line$estimate
ttest99days.with.cr.line$statistic
ttest99days.with.cr.line$method
ttest95days.with.cr.line$estimate
ttest95days.with.cr.line$statistic
ttest95days.with.cr.line$method
ttest50days.with.cr.line$estimate
ttest50days.with.cr.line$statistic
ttest50days.with.cr.line$method
```

```{r}
ttest95revol.bal = t.test(x=loans$revol.bal) # default conf.level = 0.95
ttest95revol.bal
ttest99revol.bal = t.test(x=loans$revol.bal, conf.level=0.99 )
ttest99revol.bal
ttest50revol.bal = t.test(x=loans$revol.bal, conf.level=0.50 )
ttest50revol.bal
ttest99revol.bal$estimate
ttest99revol.bal$statistic
ttest99revol.bal$method
ttest95revol.bal$estimate
ttest95revol.bal$statistic
ttest95revol.bal$method
ttest50revol.bal$estimate
ttest50revol.bal$statistic
ttest50revol.bal$method
```

```{r}
ttest95revol.util = t.test(x=loans$revol.util) # default conf.level = 0.95
ttest95revol.util
ttest99revol.util = t.test(x=loans$revol.util, conf.level=0.99 )
ttest99revol.util
ttest50revol.util = t.test(x=loans$revol.util, conf.level=0.50 )
ttest50revol.util
ttest99revol.util$estimate
ttest99revol.util$statistic
ttest99revol.util$method
ttest95revol.util$estimate
ttest95revol.util$statistic
ttest95revol.util$method
ttest50revol.util$estimate
ttest50revol.util$statistic
ttest50revol.util$method
```

```{r}
ttest95inq.last.6mths = t.test(x=loans$inq.last.6mths) # default conf.level = 0.95
ttest95inq.last.6mths
ttest99inq.last.6mths = t.test(x=loans$inq.last.6mths, conf.level=0.99 )
ttest99inq.last.6mths
ttest50inq.last.6mths = t.test(x=loans$inq.last.6mths, conf.level=0.50 )
ttest50inq.last.6mths
ttest99inq.last.6mths$estimate
ttest99inq.last.6mths$statistic
ttest99inq.last.6mths$method
ttest95inq.last.6mths$estimate
ttest95inq.last.6mths$statistic
ttest95inq.last.6mths$method
ttest50inq.last.6mths$estimate
ttest50inq.last.6mths$statistic
ttest50inq.last.6mths$method
```

```{r}
ttest95delinq.2yrs = t.test(x=loans$delinq.2yrs) # default conf.level = 0.95
ttest95delinq.2yrs
ttest99delinq.2yrs = t.test(x=loans$delinq.2yrs, conf.level=0.99 )
ttest99delinq.2yrs
ttest50delinq.2yrs = t.test(x=loans$delinq.2yrs, conf.level=0.50 )
ttest50delinq.2yrs
ttest99delinq.2yrs$estimate
ttest99delinq.2yrs$statistic
ttest99delinq.2yrs$method
ttest95delinq.2yrs$estimate
ttest95delinq.2yrs$statistic
ttest95delinq.2yrs$method
ttest50delinq.2yrs$estimate
ttest50delinq.2yrs$statistic
ttest50delinq.2yrs$method
```

```{r}
ttest95pub.rec = t.test(x=loans$pub.rec) # default conf.level = 0.95
ttest95pub.rec
ttest99pub.rec = t.test(x=loans$pub.rec, conf.level=0.99 )
ttest99pub.rec
ttest50pub.rec = t.test(x=loans$pub.rec, conf.level=0.50 )
ttest50pub.rec
ttest99pub.rec$estimate
ttest99pub.rec$statistic
ttest99pub.rec$method
ttest95pub.rec$estimate
ttest95pub.rec$statistic
ttest95pub.rec$method
ttest50pub.rec$estimate
ttest50pub.rec$statistic
ttest50pub.rec$method
```

```{r}
aovrate=aov(int.rate ~ purpose, data = loans)
aovratesummary=summary(aovrate)
aovratesummary
aovrateturkey=TukeyHSD(aovrate)
aovrateturkey
```

```{r}
aovinstallment=aov(installment ~ purpose, data = loans)
aovinstallmentsummary=summary(aovinstallment)
aovinstallmentsummary
aovinstallmentturkey=TukeyHSD(aovinstallment)
aovinstallmentturkey
```

```{r}
aovannual=aov(log.annual.inc ~ purpose, data = loans)
aovannualsummary=summary(aovannual)
aovannualsummary
aovannualturkey=TukeyHSD(aovannual)
aovannualturkey
```

```{r}
aovdti=aov(dti ~ purpose, data = loans)
aovdtisummary=summary(aovdti)
aovdtisummary
aovdtiturkey=TukeyHSD(aovdti)
aovdtiturkey
```

```{r}
aovfico=aov(fico ~ purpose, data = loans)
aovficosummary=summary(aovfico)
aovficosummary
aovficoturkey=TukeyHSD(aovfico)
aovficoturkey
```

```{r}
aovcrline=aov(days.with.cr.line ~ purpose, data = loans)
aovcrlinesummary=summary(aovcrline)
aovcrlinesummary
aovcrlineturkey=TukeyHSD(aovcrline)
aovcrlineturkey
```

```{r}
aovrbal=aov(revol.bal ~ purpose, data = loans)
aovrbalsummary=summary(aovrbal)
aovrbalsummary
aovrbalturkey=TukeyHSD(aovrbal)
aovrbalturkey
```

```{r}
aovrutil=aov(revol.util ~ purpose, data = loans)
aovrutilsummary=summary(aovrutil)
aovrutilsummary
aovrutilturkey=TukeyHSD(aovrutil)
aovrutilturkey
```

```{r}
aov6mts=aov(inq.last.6mths ~ purpose, data = loans)
aov6mtssummary=summary(aov6mts)
aov6mtssummary
aov6mtsturkey=TukeyHSD(aov6mts)
aov6mtsturkey
```

```{r}
aov2yrs=aov(delinq.2yrs ~ purpose, data = loans)
aov2yrssummary=summary(aov2yrs)
aov2yrssummary
aov2yrsturkey=TukeyHSD(aov2yrs)
aov2yrsturkey
```

```{r}
aovpubrec=aov(pub.rec ~ purpose, data = loans)
aovpubrecsummary=summary(aovpubrec)
aovpubrecsummary
aovpubrecturkey=TukeyHSD(aovpubrec)
aovpubrecturkey
```

```{r}
aovrate=aov(int.rate ~ credit.policy, data = loans)
aovratesummary=summary(aovrate)
aovratesummary
```

```{r}
aovinstallment=aov(installment ~ credit.policy, data = loans)
aovinstallmentsummary=summary(aovinstallment)
aovinstallmentsummary
```

```{r}
aovannual=aov(log.annual.inc ~ credit.policy, data = loans)
aovannualsummary=summary(aovannual)
aovannualsummary
```

```{r}
aovdti=aov(dti ~ credit.policy, data = loans)
aovdtisummary=summary(aovdti)
aovdtisummary
```

```{r}
aovfico=aov(fico ~ credit.policy, data = loans)
aovficosummary=summary(aovfico)
aovficosummary
```

```{r}
aovcrline=aov(days.with.cr.line ~ credit.policy, data = loans)
aovcrlinesummary=summary(aovcrline)
aovcrlinesummary
```

```{r}
aovrbal=aov(revol.bal ~ credit.policy, data = loans)
aovrbalsummary=summary(aovrbal)
aovrbalsummary
```

```{r}
aovrutil=aov(revol.util ~ credit.policy, data = loans)
aovrutilsummary=summary(aovrutil)
aovrutilsummary
```

```{r}
aov6mts=aov(inq.last.6mths ~ credit.policy, data = loans)
aov6mtssummary=summary(aov6mts)
aov6mtssummary
```

```{r}
aov2yrs=aov(delinq.2yrs ~ credit.policy, data = loans)
aov2yrssummary=summary(aov2yrs)
aov2yrssummary
```

```{r}
aovpubrec=aov(pub.rec ~ credit.policy, data = loans)
aovpubrecsummary=summary(aovpubrec)
aovpubrecsummary
```

```{r}
aovrate=aov(int.rate ~ not.fully.paid, data = loans)
aovratesummary=summary(aovrate)
aovratesummary
```

```{r}
aovinstallment=aov(installment ~ not.fully.paid, data = loans)
aovinstallmentsummary=summary(aovinstallment)
aovinstallmentsummary
```

```{r}
aovannual=aov(log.annual.inc ~ not.fully.paid, data = loans)
aovannualsummary=summary(aovannual)
aovannualsummary
```

```{r}
aovdti=aov(dti ~ not.fully.paid, data = loans)
aovdtisummary=summary(aovdti)
aovdtisummary
```

```{r}
aovfico=aov(fico ~ not.fully.paid, data = loans)
aovficosummary=summary(aovfico)
aovficosummary
```

```{r}
aovcrline=aov(days.with.cr.line ~ not.fully.paid, data = loans)
aovcrlinesummary=summary(aovcrline)
aovcrlinesummary
```

```{r}
aovrbal=aov(revol.bal ~ not.fully.paid, data = loans)
aovrbalsummary=summary(aovrbal)
aovrbalsummary
```

```{r}
aovrutil=aov(revol.util ~ not.fully.paid, data = loans)
aovrutilsummary=summary(aovrutil)
aovrutilsummary
```

```{r}
aov6mts=aov(inq.last.6mths ~ not.fully.paid, data = loans)
aov6mtssummary=summary(aov6mts)
aov6mtssummary
```

```{r}
aov2yrs=aov(delinq.2yrs ~ not.fully.paid, data = loans)
aov2yrssummary=summary(aov2yrs)
aov2yrssummary
```

```{r}
aovpubrec=aov(pub.rec ~ not.fully.paid, data = loans)
aovpubrecsummary=summary(aovpubrec)
aovpubrecsummary
```

```{r}
loans %>%
  select(int.rate, installment, log.annual.inc, dti, fico, days.with.cr.line, revol.bal, revol.util,
           inq.last.6mths, delinq.2yrs, pub.rec) %>%
  gather(variable, value) %>%
  ggplot(aes(sample = value)) +
  geom_qq(color = "steelblue") +
  geom_qq_line() +
  facet_wrap(~ variable, scales = "free") + # Free scales so the graphs are readable
  labs(title = "Q-Q Plots of Numeric Variables", x = "Theoretical", y = "Sample") +
  theme_minimal()
```

```{r}
test = chisq.test(table(loans$purpose,loans$credit.policy))
test
```
```{r}
test$observed
```
```{r}
test$expected
```
```{r}
test$residuals
```
```{r}
library(corrplot)
corrplot(test$residuals, is.cor = FALSE)
```

```{r}
test = chisq.test(table(loans$purpose,loans$not.fully.paid))
test
```
```{r}
test$observed
```
```{r}
test$expected
```
```{r}
test$residuals
```
```{r}
library(corrplot)
corrplot(test$residuals, is.cor = FALSE)
```

```{r}
test = chisq.test(table(loans$credit.policy,loans$not.fully.paid))
test
```
```{r}
test$observed
```
```{r}
test$expected
```
```{r}
test$residuals
```
```{r}
library(corrplot)
corrplot(test$residuals, is.cor = FALSE)
```

```{r}
sd(loans$int.rate)
sd(loans$installment)
sd(loans$log.annual.inc)
sd(loans$dti)
sd(loans$fico)
sd(loans$days.with.cr.line)
sd(loans$revol.bal)
sd(loans$revol.util)
sd(loans$inq.last.6mths)
sd(loans$delinq.2yrs)
sd(loans$pub.rec)
```

```{r}
cov(loans$int.rate,loans$installment)
cor(loans$int.rate,loans$installment)
cov(loans$int.rate,loans$log.annual.in)
cor(loans$int.rate,loans$log.annual.in)
cov(loans$int.rate,loans$dti)
cor(loans$int.rate,loans$dti)
cov(loans$int.rate,loans$fico)
cor(loans$int.rate,loans$fico)
cov(loans$int.rate,loans$days.with.cr.line)
cor(loans$int.rate,loans$days.with.cr.line)
cov(loans$int.rate,loans$revol.bal)
cor(loans$int.rate,loans$revol.bal)
cov(loans$int.rate,loans$revol.util)
cor(loans$int.rate,loans$revol.util)
cov(loans$int.rate,loans$inq.last.6mths)
cor(loans$int.rate,loans$inq.last.6mths)
cov(loans$int.rate,loans$delinq.2yr)
cor(loans$int.rate,loans$delinq.2yr)
cov(loans$int.rate,loans$pub.rec)
cor(loans$int.rate,loans$pub.rec)
cov(loans$installment,loans$log.annual.in)
cor(loans$installment,loans$log.annual.in)
cov(loans$installment,loans$dti)
cor(loans$installment,loans$dti)
cov(loans$installment,loans$fico)
cor(loans$installment,loans$fico)
cov(loans$installment,loans$days.with.cr.line)
cor(loans$installment,loans$days.with.cr.line)
cov(loans$installment,loans$revol.bal)
cor(loans$installment,loans$revol.bal)
cov(loans$installment,loans$revol.util)
cor(loans$installment,loans$revol.util)
cov(loans$installment,loans$inq.last.6mths)
cor(loans$installment,loans$inq.last.6mths)
cov(loans$installment,loans$delinq.2yr)
cor(loans$installment,loans$delinq.2yr)
cov(loans$installment,loans$pub.rec)
cor(loans$installment,loans$pub.rec)
cov(loans$log.annual.in,loans$dti)
cor(loans$log.annual.in,loans$dti)
cov(loans$log.annual.in,loans$fico)
cor(loans$log.annual.in,loans$fico)
cov(loans$log.annual.in,loans$days.with.cr.line)
cor(loans$log.annual.in,loans$days.with.cr.line)
cov(loans$log.annual.in,loans$revol.bal)
cor(loans$log.annual.in,loans$revol.bal)
cov(loans$log.annual.in,loans$revol.util)
cor(loans$log.annual.in,loans$revol.util)
cov(loans$log.annual.in,loans$inq.last.6mths)
cor(loans$log.annual.in,loans$inq.last.6mths)
cov(loans$log.annual.in,loans$delinq.2yr)
cor(loans$log.annual.in,loans$delinq.2yr)
cov(loans$log.annual.in,loans$pub.rec)
cor(loans$log.annual.in,loans$pub.rec)
cov(loans$dti,loans$fico)
cor(loans$dti,loans$fico)
cov(loans$dti,loans$days.with.cr.line)
cor(loans$dti,loans$days.with.cr.line)
cov(loans$dti,loans$revol.bal)
cor(loans$dti,loans$revol.bal)
cov(loans$dti,loans$revol.util)
cor(loans$dti,loans$revol.util)
cov(loans$dti,loans$inq.last.6mths)
cor(loans$dti,loans$inq.last.6mths)
cov(loans$dti,loans$delinq.2yr)
cor(loans$dti,loans$delinq.2yr)
cov(loans$dti,loans$pub.rec)
cor(loans$dti,loans$pub.rec)
cov(loans$fico,loans$days.with.cr.line)
cor(loans$fico,loans$days.with.cr.line)
cov(loans$fico,loans$revol.bal)
cor(loans$fico,loans$revol.bal)
cov(loans$fico,loans$revol.util)
cor(loans$fico,loans$revol.util)
cov(loans$fico,loans$inq.last.6mths)
cor(loans$fico,loans$inq.last.6mths)
cov(loans$fico,loans$delinq.2yr)
cor(loans$fico,loans$delinq.2yr)
cov(loans$fico,loans$pub.rec)
cor(loans$fico,loans$pub.rec)
cov(loans$days.with.cr.line,loans$revol.bal)
cor(loans$days.with.cr.line,loans$revol.bal)
cov(loans$days.with.cr.line,loans$revol.util)
cor(loans$days.with.cr.line,loans$revol.util)
cov(loans$days.with.cr.line,loans$inq.last.6mths)
cor(loans$days.with.cr.line,loans$inq.last.6mths)
cov(loans$days.with.cr.line,loans$delinq.2yr)
cor(loans$days.with.cr.line,loans$delinq.2yr)
cov(loans$days.with.cr.line,loans$pub.rec)
cor(loans$days.with.cr.line,loans$pub.rec)
cov(loans$revol.bal,loans$revol.util)
cor(loans$revol.bal,loans$revol.util)
cov(loans$revol.bal,loans$inq.last.6mths)
cor(loans$revol.bal,loans$inq.last.6mths)
cov(loans$revol.bal,loans$delinq.2yr)
cor(loans$revol.bal,loans$delinq.2yr)
cov(loans$revol.bal,loans$pub.rec)
cor(loans$revol.bal,loans$pub.rec)
cov(loans$revol.util,loans$inq.last.6mths)
cor(loans$revol.util,loans$inq.last.6mths)
cov(loans$revol.util,loans$delinq.2yr)
cor(loans$revol.util,loans$delinq.2yr)
cov(loans$revol.util,loans$pub.rec)
cor(loans$revol.util,loans$pub.rec)
cov(loans$inq.last.6mths,loans$delinq.2yr)
cor(loans$inq.last.6mths,loans$delinq.2yr)
cov(loans$inq.last.6mths,loans$pub.rec)
cor(loans$inq.last.6mths,loans$pub.rec)
cov(loans$delinq.2yr,loans$pub.rec)
cor(loans$delinq.2yr,loans$pub.rec)
```


```{r}
plot(loans$int.rate,loans$installment)
plot(loans$int.rate,loans$log.annual.in)
plot(loans$int.rate,loans$dti)
plot(loans$int.rate,loans$fico)
plot(loans$int.rate,loans$days.with.cr.line)
plot(loans$int.rate,loans$revol.bal)
plot(loans$int.rate,loans$revol.util)
plot(loans$int.rate,loans$inq.last.6mths)
plot(loans$int.rate,loans$delinq.2yr)
plot(loans$int.rate,loans$pub.rec)
plot(loans$installment,loans$log.annual.in)
plot(loans$installment,loans$dti)
plot(loans$installment,loans$fico)
plot(loans$installment,loans$days.with.cr.line)
plot(loans$installment,loans$revol.bal)
plot(loans$installment,loans$revol.util)
plot(loans$installment,loans$inq.last.6mths)
plot(loans$installment,loans$delinq.2yr)
plot(loans$installment,loans$pub.rec)
plot(loans$log.annual.in,loans$dti)
plot(loans$log.annual.in,loans$fico)
plot(loans$log.annual.in,loans$days.with.cr.line)
plot(loans$log.annual.in,loans$revol.bal)
plot(loans$log.annual.in,loans$revol.util)
plot(loans$log.annual.in,loans$inq.last.6mths)
plot(loans$log.annual.in,loans$delinq.2yr)
plot(loans$log.annual.in,loans$pub.rec)
plot(loans$dti,loans$fico)
plot(loans$dti,loans$days.with.cr.line)
plot(loans$dti,loans$revol.bal)
plot(loans$dti,loans$revol.util)
plot(loans$dti,loans$inq.last.6mths)
plot(loans$dti,loans$delinq.2yr)
plot(loans$dti,loans$pub.rec)
plot(loans$fico,loans$days.with.cr.line)
plot(loans$fico,loans$revol.bal)
plot(loans$fico,loans$revol.util)
plot(loans$fico,loans$inq.last.6mths)
plot(loans$fico,loans$delinq.2yr)
plot(loans$fico,loans$pub.rec)
plot(loans$days.with.cr.line,loans$revol.bal)
plot(loans$days.with.cr.line,loans$revol.util)
plot(loans$days.with.cr.line,loans$inq.last.6mths)
plot(loans$days.with.cr.line,loans$delinq.2yr)
plot(loans$days.with.cr.line,loans$pub.rec)
plot(loans$revol.bal,loans$revol.util)
plot(loans$revol.bal,loans$inq.last.6mths)
plot(loans$revol.bal,loans$delinq.2yr)
plot(loans$revol.bal,loans$pub.rec)
plot(loans$revol.util,loans$inq.last.6mths)
plot(loans$revol.util,loans$delinq.2yr)
plot(loans$revol.util,loans$pub.rec)
plot(loans$inq.last.6mths,loans$delinq.2yr)
plot(loans$inq.last.6mths,loans$pub.rec)
plot(loans$delinq.2yr,loans$pub.rec)
```


#WE NEED A left tailed test, right tailed test,shapiro test